### ISSUE TITLE
Anomolous License

### ISSUE THREAD

**Issue by alsutton** [FoldingAtHome/containers#1]
Most of the projects are licensed under GPL which can get an automatic approval from many companies to allow their employees to work on it because it's a known, long standing, license which is well understood.

This repo is licensed under CC0, which is a lesser used license, and so will increase the work needed to allow some folk to work on the project. 

Please consider altering the license to GPL or a similarly well known license (e.g. CC-BY, Apache 2, MIT, BSD, LGPL)

**Comment by beberg** [comment]
CC0 (public domain) is reasonable and the most permissive for a repo that will have Dockerfiles and configuration files which have no possibility of containing proprietary code issues. 

There is no reason to restrict it in any way, or prevent it from being reused as part of any other repo under other licenses - like the other Folding@home repos for example,

That's the reasoning, and it's unlikely to change.

**Comment by alsutton** [comment]
Thanks for the explanation of why CC0 was chosen.

The issue I'm focusing on is not the validity of CC0, just that other repos in this org already use other licenses (e.g. GPL) are well understood, and easier for folk to get approval to work on projects covered by it, and by using CC0 the friction of getting approval to work on this repo will be higher (and thus less attractive).

Please feel free to close this issue if the org is happy with the current situation.

**Comment by jchodera** [comment]
Thanks for the input! We definitely discussed other options---such as the MIT and LGPL license we use for other FAH projects (which are less restrictive than GPL). 

When possible, we follow the [reproducible research standard](https://www.google.com/url?sa=t&source=web&rct=j&url=https://web.stanford.edu/~vcs/talks/VictoriaStoddenCommuniaJune2009-2.pdf&ved=2ahUKEwjnpaeCxPLoAhW6GDQIHS2sB8IQFjABegQIBRAC&usg=AOvVaw3uw9lXHRNqI04dp4kL97Uz) which argues we should disseminate under the *least restrictive license* to ensure maximum ability to reuse, modify, and redistribute work to build on it.

While CC0 is relatively new for us, it adheres to this principle, and is endorsed by [Creative Commons](https://creativecommons.org/share-your-work/public-domain/cc0/). 

We recognize that relative novelty is not necessarily an advantage in terms of legal review, so we can discuss the potential for making things available under multiple licenses, though MIT would be more restrictive than CC0. But for various reasons, some of the contributions to this repo will have to be made under CC0.
