### ISSUE TITLE
Deployment on Synology NAS

### ISSUE THREAD

**Issue by tinne** [FoldingAtHome/containers#10]
Some NAS systems by Synology, Inc. offer for the deployment of custom images in its preconfigured integrated [Docker installment.](https://www.synology.com/en-global/dsm/feature/docker)

I have successfully deployd fah-gpu/v5.7.1 on a Synology DS 218+ two bay NAS running DSM 6.2.3-25426 Update 2 (which is a 4.4.59+ #25426 SMP PREEMPT x86_64 GNU/Linux synology_apollolake_218+). Obstacles on the way:
- integrated version is Docker version 18.09.8, build bfed4f5 (Synology version 18.09.0-0513, current of today) - this is lower than the Technical Requirements in README.md require - solved by dropping the `--gpus` switch from the docker run command
- docker run must be run on the command line (and sudoed), since the Docker GUI does not allow to set a user
- in order to use the web monitoring facilities, both the `allow` and `web-allow` config option must be correctly configured
  - a port 7398 export is added to the docker run switch list: `-p 7396:7396`
  - both syntaxes `<web-allow>ADDRESSES</web-allow>` and `<web-allow v='ADDRESSES'>` are unexpectedly equally valid methods to allow external access, the configuration `<allow v='172.17.0.1/24'/><web-allow v='172.17.0.1/24'/>` permits for web access using the standard configuration of Docker's Bridged network device

**Comment by beberg** [comment]
Are you suggesting we document this in the README?

(I also have a DS218+ and should try this...)

**Comment by tinne** [comment]
In the README or a separate installation examples file, yes.

There is one drawback on this: as in comparison to modern GPUs my Synology is quite lame, it got rejected after a while and is not allowed any further work packages—maybe the processor got blacklisted, or something else I did not understand got wrong.

@beberg So, yet another reason to give it a try.

**Comment by beberg** [comment]
It's really, really slow.

I chose not to document the web monitoring setup from the start (and the example configs have everything disabled), so users would not expose any ports in a cloud without having to go looking, since any open port is a security concern. 

Open to suggestions, or a pull request to the end of fah-gpu/README.md

**Comment by beberg** [comment]
Closing, as the device is too slow and rare to devote support to. But very very cool that it runs :)
