### ISSUE TITLE
Problem on Jetson Nano

### ISSUE THREAD

**Issue by tgrrr** [FoldingAtHome/containers#11]
Also reported here: https://github.com/FoldingAtHome/fah-issues/issues/1571

Hi,

This is failing for me on a Jetson Nano:

Steps:

```
# fah/config.xml
<config>
  <!-- Set with your user, passkey, team-->
  <user value="REDACTED"/>
  <passkey value="REDACTED"/>
  <team value="0"/>

  <power value="full"/>
  <exit-when-done v='true'/>

  <web-enable v='false'/>
  <disable-viz v='true'/>
  <gui-enabled v='false'/>

  <!-- 1 slots for GPUs -->
  <slot id='0' type='GPU'> </slot>

  <!-- 16-1 = 15 = 3*5 for decomposition -->
  <slot id='1' type='SMP'> <cpus v='15'/> </slot>

</config>
```

```zsh
$ docker run --gpus all --name fah0 -d --user "$(id -u):$(id -g)"   --volume $HOME/fah:/fah foldingathome/fah-gpu:latest
08a13874aba9145efd6b729c2b543f90e6fd250c0a880eb6721dc577816a950b
```
works

Then I run:
```zsh
$ docker start fah0
fah0
```

```zsh
~$ docker logs fah0
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
```

Prerequisites:
- [x] Pick your Username - FAQ.
- [x] Setup your Passkey. 
- [x] Join a team or create your own - FAQ.

Docker > 19
```zsh
$ docker -v
Docker version 19.03.6, build 369ce74a3c

$ nvidia-container-runtime -v
runc version spec: 1.0.1-dev
```
nvidia-container-runtime is already the newest version (3.1.0-1).

specs:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by beberg** [comment]
Jetson Nano CPU is ARM not x64, so it's not a supported platform for the container.

No plans for an ARM container at this time (few users, effort to maintain, etc), but you could open a new issue to discuss the idea.
