### ISSUE TITLE
Question about container use case to drive more cpu cycle donations

### ISSUE THREAD

**Issue by afewell** [FoldingAtHome/containers#19]
Hi I am not sure if this is the right place to open a ticket but if not I am hoping you could help point me in the right direction. 

I work for VMware and have worked for several other infrastructure companies where we burn many thousands of hours of cpu cycles every year running some random sample application, where the sample app itself has no point, its just needed to have some app to demonstrate our infrastructure software underneath. 

I would like to see if its possible to turn at least some demo use cases into demos that could use folding@home as our sample workload. I am just starting to investigate this idea and dont yet know basic things like what is the minimal hardware requirement a container running folding@home would need or how long does a container need to run to create at least a minimal or greater benefit. 

I realize this use case may not work well for all of our demos, but we have a lot of different types of demos and I am very hopeful we could find demo types that could make a meaningful contribution of cpu cycles. For example while most of our demo apps are short running, I am proposing some ideas for events where we may partner with an organization like folding@home to run larger scale demos that may run for a day or multiple days. Even during shorter demos, we often have our engineers access a temporary environment for their demo that continues to run for some period of time after they finish giving the demo, sometimes for multiple days or weeks. 

I am actively trying to pursue exploring this idea within VMware and am not sure how quickly I will make progress, but if you have any advice or guidance I would be very grateful. 

Thank you!

**Comment by jchodera** [comment]
Thanks so much for suggesting this, @afewell! We'd be delighted to help you out. Could you email me directly at john.chodera@choderalab.org? I'll be happy to put you in touch with our developers directly to provide assistance, and we can continue to add any improvements/refinements to this repository.
