### ISSUE TITLE
Are the dev libraries and compilers needed for fah-gpu-amd?

### ISSUE THREAD

**Issue by sanori** [FoldingAtHome/containers#22]
The size of the current fah-gpu-amd image is about 3.9GB.
It is too large compared to 92.1MB of the size of fah-gpu (Nvidia CUDA).

Currently, fah-gpu-amd installs the `rocm-dev` package, which depends on the ROCm runtime and development libraries and LLVM compilers that rely on the g++ development environment.

I guess that this image's goal is to provide OpenMM, precisely speaking OpenCL, runtime to run [the FAH core 22](https://en.wikipedia.org/wiki/List_of_Folding@home_cores#GPU3) efficiently.
If my guess is correct, only the runtimes related to OpenCL acceleration would be enough.

**Comment by beberg** [comment]
#23 accepted, thanks.
