### ISSUE TITLE
Please test fah-gpu-amd container

### ISSUE THREAD

**Issue by beberg** [FoldingAtHome/containers#25]
@mharsch 
@sanori 

I just pushed `foldingathome/fah-gpu-amd:22.01.0-rc1` to Docker Hub, can one/both of you verify it's a good image on your systems, and also check the README wasn't mangled by the slight differences in GitHub and Docker markdown?

https://hub.docker.com/r/foldingathome/fah-gpu-amd

If all is well, I will push `21.01.0` and `latest` tags.

Thanks.

**Comment by mharsch** [comment]
Well, a quick test on one of my AMD machines did not pass right away, and is going to require some troubleshooting.  The combination of host OS (Ubuntu 20.04.3), host kernel version (5.4), host AMD driver/ROCm version (4.5), and container ROCm runtime version (4.3.1) is all in play.

mharsch@meraxes:~$ docker logs fah3
22:04:50:Read GPUs.txt
22:04:50:******************************* libFAH ********************************
22:04:50:           Date: Oct 20 2020
22:04:50:           Time: 20:36:39
22:04:50:       Revision: 5ca109d295a6245e2a2f590b3d0085ad5e567aeb
22:04:50:         Branch: master
22:04:50:       Compiler: GNU 8.3.0
22:04:50:        Options: -faligned-new -std=c++11 -fsigned-char -ffunction-sections
22:04:50:                 -fdata-sections -O3 -funroll-loops -fno-pie
22:04:50:       Platform: linux2 5.8.0-1-amd64
22:04:50:           Bits: 64
22:04:50:           Mode: Release
22:04:50:****************************** FAHClient ******************************
22:04:50:        Version: 7.6.21
22:04:50:         Author: Joseph Coffland <joseph@cauldrondevelopment.com>
22:04:50:      Copyright: 2020 foldingathome.org
22:04:50:       Homepage: https://foldingathome.org/
22:04:50:           Date: Oct 20 2020
22:04:50:           Time: 20:39:00
22:04:50:       Revision: 6efbf0e138e22d3963e6a291f78dcb9c6422a278
22:04:50:         Branch: master
22:04:50:       Compiler: GNU 8.3.0
22:04:50:        Options: -faligned-new -std=c++11 -fsigned-char -ffunction-sections
22:04:50:                 -fdata-sections -O3 -funroll-loops -fno-pie
22:04:50:       Platform: linux2 5.8.0-1-amd64
22:04:50:           Bits: 64
22:04:50:           Mode: Release
22:04:50:           Args: --chdir /fah
22:04:50:         Config: /fah/config.xml
22:04:50:******************************** CBang ********************************
22:04:50:           Date: Oct 20 2020
22:04:50:           Time: 18:37:59
22:04:50:       Revision: 7e4ce85225d7eaeb775e87c31740181ca603de60
22:04:50:         Branch: master
22:04:50:       Compiler: GNU 8.3.0
22:04:50:        Options: -faligned-new -std=c++11 -fsigned-char -ffunction-sections
22:04:50:                 -fdata-sections -O3 -funroll-loops -fno-pie -fPIC
22:04:50:       Platform: linux2 5.8.0-1-amd64
22:04:50:           Bits: 64
22:04:50:           Mode: Release
22:04:50:******************************* System ********************************
22:04:50:            CPU: AMD Ryzen 7 2700X Eight-Core Processor
22:04:50:         CPU ID: AuthenticAMD Family 23 Model 8 Stepping 2
22:04:50:           CPUs: 16
22:04:50:         Memory: 15.62GiB
22:04:50:    Free Memory: 13.72GiB
22:04:50:        Threads: POSIX_THREADS
22:04:50:     OS Version: 5.4
22:04:50:    Has Battery: false
22:04:50:     On Battery: false
22:04:50:     UTC Offset: 0
22:04:50:            PID: 1
22:04:50:            CWD: /fah
22:04:50:             OS: Linux 5.4.0-97-generic x86_64
22:04:50:        OS Arch: AMD64
22:04:50:           GPUs: 1
22:04:50:          GPU 0: Bus:12 Slot:0 Func:0 AMD:5 Vega 20 [Radeon VII] 13,284
22:04:50:           CUDA: Not detected: Failed to open dynamic library 'libcuda.so':
22:04:50:                 libcuda.so: cannot open shared object file: No such file or
22:04:50:                 directory
22:04:50:OpenCL Device 0: Platform:0 Device:0 Bus:12 Slot:0 Compute:2.0 Driver:3305.0
22:04:50:***********************************************************************
22:04:50:<config>
22:04:50:  
22:04:50:  <exit-when-done v='true'/>
22:04:50:
22:04:50:  
22:04:50:  <disable-viz v='true'/>
22:04:50:
22:04:50:  
22:04:50:  <gui-enabled v='false'/>
22:04:50:
22:04:50:  
22:04:50:  <power v='full'/>
22:04:50:
22:04:50:  
22:04:50:  <passkey v='*****'/>
22:04:50:  <user v='mharsch'/>
22:04:50:
22:04:50:  
22:04:50:  <slot id='0' type='GPU'>
22:04:50:    <pci-bus v='12'/>
22:04:50:    <pci-slot v='0'/>
22:04:50:  </slot>
22:04:50:</config>
22:04:50:Trying to access database...
22:04:50:Successfully acquired database lock
22:04:50:FS00:Initialized folding slot 00: gpu:12:0 Vega 20 [Radeon VII] 13,284
22:04:50:WU01:FS00:Cleaning up
22:04:50:WU00:FS00:Connecting to assign1.foldingathome.org:80
22:04:51:WU00:FS00:Assigned to work server 128.252.203.10
22:04:51:WU00:FS00:Requesting new work unit for slot 00: gpu:12:0 Vega 20 [Radeon VII] 13,284  from 128.252.203.10
22:04:51:WU00:FS00:Connecting to 128.252.203.10:8080
22:04:52:WU00:FS00:Downloading 50.53MiB
22:04:57:WU00:FS00:Download complete
22:04:57:WU00:FS00:Received Unit: id:00 state:DOWNLOAD error:NO_ERROR project:17257 run:952 clone:2 gen:31 core:0x22 unit:0x000000020000001f00004369000003b8
22:04:57:WU00:FS00:Starting
22:04:57:WU00:FS00:Running FahCore: /usr/bin/FAHCoreWrapper /fah/cores/cores.foldingathome.org/lin/64bit/22-0.0.20/Core_22.fah/FahCore_22 -dir 00 -suffix 01 -version 706 -lifeline 1 -checkpoint 15 -opencl-platform 0 -opencl-device 0 -gpu-vendor amd -gpu 0 -gpu-usage 100
22:04:57:WU00:FS00:Started FahCore on PID 16
22:04:57:WU00:FS00:Core PID:20
22:04:57:WU00:FS00:FahCore 0x22 started
22:04:57:WARNING:WU00:FS00:FahCore returned: BAD_WORK_UNIT (114 = 0x72)
22:04:57:WU00:FS00:Sending unit results: id:00 state:SEND error:FAULTY project:17257 run:952 clone:2 gen:31 core:0x22 unit:0x000000020000001f00004369000003b8
22:04:57:WU00:FS00:Uploading 9.50KiB to 128.252.203.10
22:04:57:WU00:FS00:Connecting to 128.252.203.10:8080
22:04:58:WU00:FS00:Upload complete
22:04:58:WU00:FS00:Server responded WORK_ACK (400)
22:04:58:WU00:FS00:Cleaning up
22:04:58:WU01:FS00:Connecting to assign1.foldingathome.org:80
22:04:58:WU01:FS00:Assigned to work server 128.252.203.10
22:04:58:WU01:FS00:Requesting new work unit for slot 00: gpu:12:0 Vega 20 [Radeon VII] 13,284  from 128.252.203.10
22:04:58:WU01:FS00:Connecting to 128.252.203.10:8080
22:04:59:WU01:FS00:Downloading 50.56MiB
22:05:04:WU01:FS00:Download complete
22:05:04:WU01:FS00:Received Unit: id:01 state:DOWNLOAD error:NO_ERROR project:17257 run:1592 clone:1 gen:19 core:0x22 unit:0x00000001000000130000436900000638
22:05:04:WU01:FS00:Starting
22:05:04:WU01:FS00:Running FahCore: /usr/bin/FAHCoreWrapper /fah/cores/cores.foldingathome.org/lin/64bit/22-0.0.20/Core_22.fah/FahCore_22 -dir 01 -suffix 01 -version 706 -lifeline 1 -checkpoint 15 -opencl-platform 0 -opencl-device 0 -gpu-vendor amd -gpu 0 -gpu-usage 100
22:05:04:WU01:FS00:Started FahCore on PID 23
22:05:04:WU01:FS00:Core PID:27
22:05:04:WU01:FS00:FahCore 0x22 started
22:05:04:WARNING:WU01:FS00:FahCore returned: BAD_WORK_UNIT (114 = 0x72)
22:05:04:WU01:FS00:Sending unit results: id:01 state:SEND error:FAULTY project:17257 run:1592 clone:1 gen:19 core:0x22 unit:0x00000001000000130000436900000638
22:05:04:WU01:FS00:Uploading 9.50KiB to 128.252.203.10
22:05:04:WU01:FS00:Connecting to 128.252.203.10:8080
22:05:04:WU01:FS00:Upload complete
22:05:04:WU01:FS00:Server responded WORK_ACK (400)
22:05:04:WU01:FS00:Cleaning up

<< Above cycle repeats>>

**Comment by beberg** [comment]
Any luck with further testing @mharsch ?

**Comment by mharsch** [comment]
Sorry for dragging on this.  So far, I've been unable to get this version of the container to work on current ROCm host configs (e.g. 4.5 and 5.0) with the above mentioned failure mode.

I have been able to get a ROCm 5.0 fah-gpu-amd container to work on a ROCm 5.0 host as of today (ROCm 5.0 was just released).

**Comment by jchodera** [comment]
@mharsch : If it's easier to pull you into the slack to help debug, we'd be happy to do that! Might be easier to have you run a test workload so we can better inspect the failure logs. Just shoot me an email---my contact info is here: https://www.choderalab.org/members

**Comment by beberg** [comment]
@mharsch that's great news that 5 on 5 works, I'm not opposed to telling people they need to have the lateest, but if we could get a 5 container to work on 4.5 that would be more portable.

**Comment by beberg** [comment]
Awesome @mharsch , put in a PR and I'll push a new 22.02.0-rc2

**Comment by mharsch** [comment]
@beberg see #26 

On a related note: do we have a preference for the container base image (18.04 vs 20.04)?  I've left it at 18.04 for now.

**Comment by beberg** [comment]
@mharsch `foldingathome/fah-gpu-amd:22.02.0-rc1` pushed to Docker Hub ready to test...

**Comment by mharsch** [comment]
foldingathome/fah-gpu-amd:22.02.0-rc1 looks good; I've got it folding on 2 different machines.

I did notice that the README needed a change to the new ROCm doc site.  See new PR #27

**Comment by beberg** [comment]
#27 merged, tags `22.02.0` and `latest` pushed. Thanks @mharsch !!!

**Comment by mharsch** [comment]
One more data point: I got this container working on a recent consumer card (RX 6600).  These are not officially supported by AMD on ROCm, but as of 4.5/5.0 the opencl stack started working on these Navi/RDNA cards.
`21:57:33:FS00:Initialized folding slot 00: gpu:47:0 Navi 23 [Radeon RX 6600/6600 XT/6600M]`
