### ISSUE TITLE
Explain performance penalty of running Folding@home in container

### ISSUE THREAD

**Issue by abitrolly** [FoldingAtHome/containers#7]
The `README.md` outlines so many benefits, but completely misses the part about performance. I think that for distributed computing community the performance is very important topic to cover.

https://hackernoon.com/another-reason-why-your-docker-containers-may-be-slow-d37207dec27f

**Comment by beberg** [comment]
This is fair, adding a bit to the README where it talks about using the standard clients if you're not familiar with containers already. Will be in next update.

**Comment by abitrolly** [comment]
@beberg actually I expected the upcoming explanation to be targeted to people who are already familiar with containers. )

**Comment by abitrolly** [comment]
@beberg there is still no information if running Folding@home in a container is slower and to what degree. Especially interesting to benchmark various container runtimes like https://github.com/FoldingAtHome/containers/commit/681d53f746a64547a64418cbea353a99cca038db
