### ISSUE TITLE
Deployment and performance on Google Cloud Platform

### ISSUE THREAD

**Issue by sgnsajgon** [FoldingAtHome/containers#8]
I have deployed fah-gpu container on Google Kubernetes Engine (Google Cloud Platform). Currently I'm using cluster with one node:

Machine type: n1-standard-1 (1 vCPU, 3.75 GB memory)
CPU: Intel(R) Xeon(R) CPU @ 2.20GHz, GenuineIntel Family 6 Model 79 Stepping 0
OS: Container-Optimized OS
GPU: NVIDIA Tesla T4
Preemptible VM

I'm running single GPU folding slot, and it works well - GPU yields ~800-850k points per day, and is able to process very massive work units in reasonable amount of time. However, I wonder if it is possible to increase my GPU performance, so I have 3 issues, which probably are worth to be discussed and noted in Readme file.

1) When I inspect cluster resources utilization, I get the following, typical values:

```
sgnsajgon@cloudshell:~$ kubectl top nodes
NAME                                                  CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
gke-folding-at-home-n1-std-1-tesla-t4-0eeec1f6-7rlh   1000m        106%   1758Mi          66%
```
```
sgnsajgon@cloudshell:~$ kubectl top pods
NAME                          CPU(cores)   MEMORY(bytes)
fahclient-gpu-statefulset-0   955m         739Mi
```

We can see that node CPU is fully utilized, almost entirely consumed by fahclient Pod (there are also other kube-system Pods deployed on this node, but they do not consume much of resources).

Is it possible that if I deploy fah-gpu on faster or more modern CPU, then I will get better GPU performance? Which CPU (in terms of it's parameters) is the optimal choice for my GPU, and in general, for other GPUs in context of fah-gpu container? How can we check whether we get maximum performance out of our GPUs?

2) Will I get any performance boost if I use newer CUDA toolkit than 9.2, for example if I use newer base Docker image, i.e. 10.1-base-ubuntu18.04, or the latest?

3) I'm thinking about scaling up my cluster. Which option would be better in context of performance - running 2 GPUs (and 2 vCPUs and more RAM) on single node (vertical scaling), or running two separate nodes, each having 1 GPU and 1 vCPU (horizontal scaling).

I think some information and tips on this subject would be greatly appreciated.

Thank you so much, great job, I'm looking forward to new features.

**Comment by beberg** [comment]
Deploying to cloud isn't cheap, so we don't generally see that done.

1. Yes, the clients by default consumes whatever resources are available. Faster resources are better but more $$$/hour.
2. Newer CUDA shouldn't matter, and recent drivers should all work. The code does not use Tensor cores or RTX features.
3. Both are fine, but you have to make sure reach client has it's own persistent storage directory to keep state.
